include:
  - project: "GNOME/citemplates"
    file: "templates/default-rules.yml"
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: "build-release-tarball"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

variables:
  TARBALL_ARTIFACT_PATH: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

build-release-tarball:
  image: "quay.io/gnome_infrastructure/gnome-build-meta:sdk-47"
  stage: "build"
  script:
    - ./autogen.sh --prefix=/usr --libdir=/usr/lib/$(gcc -print-multiarch)
    - make --jobs=$(nproc)
    - make --jobs=$(nproc) distcheck
  artifacts:
    expire_in: "2 days"
    when: "always"
    paths:
      - "${TARBALL_ARTIFACT_PATH}"

